# docker-compose.yml
version: '3'

services:
  app:
    build: .
    image: app:local
    ports:
      # Service will be accessible on the host at port 9090.
      - "9090:${PORT:-8080}"
    environment:
      # /run/docs/reference/container-contract
      PORT: ${PORT:-8080}
      K_SERVICE: app
      K_REVISION: 0
      K_CONFIGURATION: app
